name: test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: clone vcpkg
        run: git clone https://github.com/Microsoft/vcpkg.git

      - name: setup vcpkg
        run: ./vcpkg/bootstrap-vcpkg.sh
      
